### ISSUE TITLE
feature request: list of property-value pairs to be set in the cookie

### ISSUE THREAD

**Issue by wizardfan** [andreasonny83/angular2-cookie-law#19]
Hi Andrea,

It is a great module which allows me to implement basic cookie law with only several lines of codes. If I understand correctly, this module store a cookie on the client computer with only one property: name. Does this mean that if two users use the the same computer and the first user accepts the cookie, the second user will not be prompted the banner?

What I am suggesting to allow taking in a data structure like 

```
{ 
  user: john smith,
  name: cookie-law,
  date: 09/05/2018
}
```

which could make the module more flexible, e.g. if the terms and conditions changes, the cookie banner could be popped again.

Best regards,
Jun

**Comment by andreasonny83** [comment]
Sorry but I don't know when I will have the time to make that implementation.
I will be more than happy to accept your pull request if you can. That will speed up the process for sure.
Thanks for the suggestion @wizardfan

**Comment by andreasonny83** [comment]
I'm reading agin through your comment and I probably misunderstood the requirement initially.

So:
If 2 different users open the same website from the same machine
And if they're using 2 different browsers or browsers accounts (In Chrome you can easily switch between Chrome accounts)
Then both the users will be asked to accept the cookie policy because the cookie information is stored inside the browser localStorage which is not shared between browsers instances.
So you should never have this kind of problem.

If, however, 2 different users are using the same browser and the same browser account
Then you can still bind your cookie banner down to a specific user if you have that information inside your application.
For this second scenario, you can do something like this:
```
<cookie-law name={{usernameCookie}}></cookie-law>
```

```
this.usernameCookie = `${this.username}_cookie_seen`;
```
